apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: june19-test-nodb
  janus-idp.io/tekton: june19-test-nodb
  backstage.io/kubernetes-id: june19-test-nodb
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: june19-test-nodb
resources:
  - application-dev.yaml