apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: june19-test-nodb-gitops
  description: This is GitOps manifest for june19-test-nodb   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=june19-test-nodb
    janus-idp.io/tekton: june19-test-nodb 
    backstage.io/kubernetes-id: june19-test-nodb 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:june19-test-nodb  
